server:
  port: 9001
spring:
  application:
    name: user-service
  main:
    allow-bean-definition-overriding: true

  cloud:
    nacos:
      discovery:
        server-addr:
      config:
        server-addr:
        file-extension: yaml

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect