server:
  port: 8500
spring:
  application:
    name: oauth2-service
  main:
    allow-bean-definition-overriding: true

  cloud:
    nacos:
      discovery:
        server-addr:
      config:
        server-addr:
        file-extension: yaml

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/oauth2?serverTimezone=UTC&useSSL=false

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect